name: Deploy yotas documentation

on:
  push:
    branches:
      'main/doc'
jobs:
  hostme_deployment_job:
    runs-on: ubuntu-latest
    name: Hostme.Space deployment
    defaults:
      run:
        working-directory: ./docs/backend 
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install && yarn build
      - id: deployment
        uses: osscameroon/hostme.gh-action@v2
        with:
          project-zip: 'doc_yotas.zip'
          hostme-project-name: 'doc_yotas'
          hostme-api-token: '${{ secrets.HOSTME_API_TOKEN }}'
          # We zip the project by excluding .git subdirectory
          # (but if we want to build something, we can add those commands here)
          commands: |
            echo [-] Zipping of the project in progress...
            zip -r doc_yotas.zip ./build -x '*.git*'
      # We delete the zip we just created
      - run: |
          echo Cleaning in progress....
          rm -rf doc_yotas.zip
        shell: bash
