name: Deploy yotas documentation

on: [push]

jobs:
  hostme_deployment_job:
    runs-on: ubuntu-latest
    name: Hostme.Space doc deployment

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js setupnode
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Use osscamerooon github action
        uses: osscameroon/hostme.gh-action@v2
        with:
          project-zip: 'doc-yotas.zip'
          hostme-project-name: 'doc-yotas'
          hostme-api-token: '${{ secrets.HOSTME_API_TOKEN }}'
          # We zip the project by excluding .git subdirectory
          # (but if we want to build something, we can add those commands here)
          commands: |
            cd ./docs/backend
            yarn install && yarn build
            echo [-] Zipping of the project in progress...
            cd ./build && zip -r 'doc-yotas.zip' .
      # We delete the zip we just created
      - run: |
          echo Cleaning in progress....
          cd ./docs/backend
          rm -rf 'doc-yotas.zip'
        shell: bash
