name: Deploy yotas documentation

on:
  push:
    branches:
      - 'deploy/doc'

jobs:
  hostme_deployment_job:
    runs-on: ubuntu-latest
    name: Hostme.Space deployment
    defaults:
      run:
        working-directory: ./docs/backend 
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        uses: osscameroon/hostme.gh-action@v2
        working-directory: ./docs/backend 
        with:
          project-zip: 'doc-yotas.zip'
          hostme-project-name: 'doc-yotas'
          hostme-api-token: '${{ secrets.HOSTME_API_TOKEN }}'
          # We zip the project by excluding .git subdirectory
          # (but if we want to build something, we can add those commands here)
          commands: |
            yarn install && yarn build
            echo [-] Zipping of the project in progress...
            cd ./build && zip -r 'doc-yotas.zip' .
      # We delete the zip we just created
      - run: |
          echo Cleaning in progress....
          rm -rf 'doc-yotas.zip'
        shell: bash
