name: Deploy yotas documentation

on: [push]

jobs:
  hostme_deployment_job:
    runs-on: ubuntu-latest
    name: Hostme.Space doc deployment

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js setupnode
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Use osscamerooon github action
        uses: osscameroon/hostme.gh-action@v3
        with:
          api-token: '${{ secrets.HOSTME_API_TOKEN }}'
          commands: |
            cd ./docs/backend
            yarn install && yarn build
            echo "doc-yotas" > h_name.out
            echo "./build" > h_target.out
